function ustAramaGUI(arayan, aranan)
	local screenW, screenH = guiGetScreenSize()
    ustAramaSorWindow = guiCreateWindow((screenW - 455) / 2, (screenH - 141) / 2, 455, 141, "Reval Roleplay - Üst Arama Sistemi", false)
    guiWindowSetSizable(ustAramaSorWindow, false)
    aramaTheLabel = guiCreateLabel(12, 25, 433, 40, getPlayerName(arayan) .. " isimli kişi üzerinizi aramak istiyor, kabul ediyor musunuz?", false, ustAramaSorWindow)
    guiLabelSetHorizontalAlign(aramaTheLabel, "center", true)
    guiLabelSetVerticalAlign(aramaTheLabel, "center")
    aramaKabulEtSorBtn = guiCreateButton(12, 75, 215, 50, "Evet", false, ustAramaSorWindow)
    guiSetProperty(aramaKabulEtSorBtn, "NormalTextColour", "FFAAAAAA")
	addEventHandler("onClientGUIClick", aramaKabulEtSorBtn, function() if source == aramaKabulEtSorBtn then  destroyElement(ustAramaSorWindow) triggerServerEvent( "ustuKabulet", arayan, arayan, aranan) end end)
    aramaReddetBtn = guiCreateButton(235, 75, 210, 50, "Hayır", false, ustAramaSorWindow)
    guiSetProperty(aramaReddetBtn, "NormalTextColour", "FFAAAAAA")
	addEventHandler("onClientGUIClick", aramaReddetBtn, function() if source == aramaReddetBtn then destroyElement(ustAramaSorWindow) triggerServerEvent("ustuReddet", arayan, arayan, aranan) end end)
end
addEvent("ustunuArama", true)
addEventHandler("ustunuArama", root, ustAramaGUI)